# Generated by Django 2.1 on 2019-10-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='текст сообщения')),
                ('message_author', models.CharField(max_length=50, verbose_name='автор сообщения')),
                ('message_time', models.DateTimeField(verbose_name='дата публикации')),
            ],
        ),
    ]
